blueprint:
    name: Blind automation configurator
    description: This blueprints is used to open and close blinds based on the time of day.
    domain: automation
    input: 
        blinds:
          name: Blind selector
          description: Which blinds to automate
          default: []
          selector:
            target:
              entity:
                domain: cover
        open_time:
          name: Opening Time
          description: When to open the blinds.
          default: "00:00:00"
          selector:
            time:
        open_blinds:
          name: Open blinds position
          description: Position to close the blinds to
          default: 75
          selector:
            number:
              min: 0
              max: 100
        close_time:
          name: Closing Time
          description: When to close the blinds.
          default: "00:00:00"
          selector:
            time:
        close_blinds:
          name: Close blinds position
          description: Position to close the blinds to
          default: 0
          selector:
            number:
              min: 0
              max: 100
        weekday:
          name: Day of the week to use the Automation
          default: [mon, tue, wed, thu, fri, sat, sun]
          selector:
            select:
              options:
              - label: Monday
                value: mon
              - label: Tuesday
                value: tue
              - label: Wednesday
                value: wed
              - label: Thursday
                value: thu
              - label: Friday
                value: fri
              - label: Saturday
                value: sat
              - label: Sunday
                value: sun
              multiple: true
trigger:
  - platform: time
    at: !input open_time
  - platform: time
    at: !input close_time

action:
  - choose:
      - conditions:
          - condition: time
            weekday: !input 'weekday'
            after: !input open_time
        sequence:
          - service: cover.set_cover_position
            data:
              position: !input open_blinds
            target:
              device_id: !input 'blinds'
      - conditions:
          - condition: time
            weekday: !input 'weekday'
            after: !input close_time
        sequence:
          - service: cover.set_cover_position
            data:
              position: !input close_blinds
            target:
              device_id: !input 'blinds'