blueprint:
    name: Cover automation configurator
    description: This blueprint is used to open and close covers based on the time of day.
    domain: automation
    input: 
        covers:
          name: Cover selector
          description: Which covers to automate
          selector:
            target:
              entity:
                domain: cover
        open_time:
          name: Opening Time
          description: When to open the covers.
          default: "00:00:00"
          selector:
            time:
        open_covers:
          name: Open covers position
          description: Position to close the covers to.
          default: 75
          selector:
            number:
              min: 0
              max: 100
        close_time:
          name: Closing Time
          description: When to close the covers.
          default: "00:00:00"
          selector:
            time:
        close_covers:
          name: Close covers position
          description: Position to close the covers to.
          default: 0
          selector:
            number:
              min: 0
              max: 100
        weekday:
          name: Day of the week to use the Automation
          default: [mon, tue, wed, thu, fri, sat, sun]
          selector:
            select:
              options:
              - label: Monday
                value: mon
              - label: Tuesday
                value: tue
              - label: Wednesday
                value: wed
              - label: Thursday
                value: thu
              - label: Friday
                value: fri
              - label: Saturday
                value: sat
              - label: Sunday
                value: sun
              multiple: true
trigger:
  - platform: time
    at: !input open_time
  - platform: time
    at: !input close_time

action:
  - choose:
      - conditions:
          - condition: time
            weekday: !input 'weekday'
            after: !input open_time
        sequence:
          - service: cover.set_cover_position
            data:
              position: !input open_covers
            target: !input covers
      - conditions:
          - condition: time
            weekday: !input 'weekday'
            after: !input close_time
        sequence:
          - service: cover.set_cover_position
            data:
              position: !input close_covers
            target: !input covers