blueprint:
    name: Power Toggler
    description: This blueprint is used to toggle devices based on power usage.
    domain: automation
    input: 
        power:
          name: Trigger device
          description: Select which devices to trigger from.
          selector:
            device:
        delay:
          name: Delay timer
          description: How long to delay the automation after Wattage change.
          default: "00:00:00"
          selector:
            time:
        turn_on:
          name: Power on
          description: When to turn on devices.
          default: 7500
          selector:
            number:
              unit_of_measurement: "W"
              step: 500
              min: 5000
              max: 15000
        turn_off:
          name: Power off
          description: When to turn off devices.
          default: 8000
          selector:
            number:
              unit_of_measurement: "W"
              step: 500
              min: 5000
              max: 15000
        conditon:
          name: Conditional elements
          description: Select which devices to automate.
          selector:
            device:
        entities:
          name: Target entities
          description: Select which devices to automate.
          selector:
            target:
              entities:

trigger:
  - platform: device
    id: trigger_on
    device_id: !input power
    domain: sensor
    below: !input turn_on
    for: !input delay
  - platform: device
    id: trigger_off
    device_id: !input power
    domain: sensor
    above: !input turn_off
    for: !input delay


condition:
  - condition: device
    type: is_off
    device_id: 85c5dfda20fa91c08952501f22646fb2
    entity_id: switch.varmtvannstank
    domain: switch

action:
  - choose:
      - conditions:
          - condition: trigger
            id: trigger_on
        sequence:
          - service: switch.turn_on //figure out how to create an if statement for climate and switch
            target: !input entities
      - conditions:
          - condition: trigger
            id: trigger_off
        sequence:
          - service: switch.turn_off //figure out how to create an if statement for climate and switch
            target: !input entities