blueprint:
    name: Power Toggler
    description: This blueprint is used to toggle devices based on power usage.
    domain: automation
    input: 
        power:
          name: Trigger device
          description: Select which devices to trigger power usage from.
          selector:
            device:
        delay_on:
          name: Delay timer on (minutes)
          description: How long to delay the automation after Wattage change.
          default: 0
          selector:
            number:
              min: 0
              max: 60
        turn_on:
          name: Power on
          description: When to turn on devices.
          default: 7500
          selector:
            number:
              unit_of_measurement: "W"
              step: 500
              min: 5000
              max: 15000
        action_on:
          name: Target action when on
          description: If you want to enable conditions before runtime, add a condition in the front of the actions.
          selector:
            action:
        delay_off:
          name: Delay timer off (minutes)
          description: How long to delay the automation after Wattage change.
          default: 0
          selector:
            number:
              min: 0
              max: 60
        turn_off:
          name: Power off
          description: When to turn off devices.
          default: 8000
          selector:
            number:
              unit_of_measurement: "W"
              step: 500
              min: 5000
              max: 15000
        action_off:
          name: Target action when off
          description: If you want to enable conditions before runtime, add a condition in the front of the actions.
          selector:
            action:

trigger:
  - platform: device
    id: trigger_on
    device_id: !input power
    domain: sensor
    below: !input turn_on
    for: !input delay_on
  - platform: device
    id: trigger_off
    device_id: !input power
    domain: sensor
    above: !input turn_off
    for: !input delay_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: trigger_on
        sequence: !input action_on
      - conditions:
          - condition: trigger
            id: trigger_off
        sequence: !input action_off