blueprint:
    name: Power Toggler
    description: This blueprint is used to toggle devices based on power usage.
    domain: automation
    input: 
        power:
          name: Trigger device
          description: Select which devices to trigger from.
          selector:
            device:
        delay:
          name: Delay timer
          description: How long to delay the automation after Wattage change.
          default: "00:00:00"
          selector:
            time:
        turn_on:
          name: Power on
          description: When to turn on devices.
          default: 7500
          selector:
            number:
              unit_of_measurement: "W"
              step: 500
              min: 5000
              max: 15000
        turn_off:
          name: Power off
          description: When to turn off devices.
          default: 8000
          selector:
            number:
              unit_of_measurement: "W"
              step: 500
              min: 5000
              max: 15000
        action_on:
          name: Target action when on
          description: 
          selector:
            action:
        action_off:
          name: Target action when off
          description: 
          selector:
            action:
        condition_on:
          name: Condition to turn on
          description: 
          selector:
            condition:
        condition_off:
          name: Condition to turn off
          description: 
          selector:
            condition:

trigger:
  - platform: device
    id: trigger_on
    device_id: !input power
    domain: sensor
    below: !input turn_on
    for: !input delay
  - platform: device
    id: trigger_off
    device_id: !input power
    domain: sensor
    above: !input turn_off
    for: !input delay

action:
  - choose:
      - conditions:
          - condition: trigger
            id: trigger_on
        sequence:
          - condition: !input condition_on
          - action: !input action_on
      - conditions:
          - condition: trigger
            id: trigger_off
        sequence:
          - condition: !input condition_off
          - action: !input action_off