blueprint:
    name: Power Toggler
    description: This blueprint is used to toggle devices based on power usage.
    domain: automation
    input: 
        power:
          name: Trigger device
          description: Select which devices to trigger from.
          selector:
            device:
        delay:
          name: Delay timer
          description: How long to delay the automation after Wattage change.
          default: "00:00:00"
          selector:
            time:
        turn_on:
          name: Power on
          description: When to turn on devices.
          default: 7500
          selector:
            number:
              unit_of_measuremen: "W"
              step: 500
              min: 5000
              max: 15000
        turn_off:
          name: Power off
          description: When to turn off devices.
          default: 8000
          selector:
            number:
              unit_of_measuremen: "W"
              step: 500
              min: 5000
              max: 15000
        action:
          name: Target action
          description: Select what to automate.
          selector:
            action:

trigger:
  - platform: device
    id: trigger_on
    device_id: !input power
    domain: sensor
    below: !input turn_on
    for: !input delay
  - platform: device
    id: trigger_off
    device_id: !input power
    domain: sensor
    above: !input turn_off
    for: !input delay

action:
  - choose:
      - conditions:
          - condition: trigger
            id: trigger_on
        sequence:
          - service: !input action
      - conditions:
          - condition: trigger
            id: trigger_off
        sequence:
          - service: !input action